### ISSUE TITLE
Get involved page

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/Main-Website#11]
Have a full get involved page with a bunch of information for potential new members. Suggested wording from [abandoned dev site](http://dev.nottinghamtec.co.uk/about/join-tec/). Would require some rewording to make sense on the new site.

> At TEC, we are always welcoming new members. The easiest way to join is to use the University of Nottingham Students’ Union website.
> 
> Our membership is free of charge, and we encourage you to come on as many or as few rigs as you can, providing suitable training and lots of fun. Membership is open exclusively to students of the University of Nottingham, though we do have an extensive network of alumni who, while no longer students, are still members.
> 
> If you’d like to join, go to our page on the Students’ Union website and click sign up – it’s free! If you have any questions, either contact us online, or come into our office – on the C Floor, Portland Building, University Park Campus.
> 
> We hold two New Members’ Introduction sessions each academic year, around Freshers’ and Re-Freshers’ Fair. Of course, you can join any time, but attending these will give you an insight into what TEC is about and provide the necessary initial health & safety training.

**Comment by tomtom5152** [comment]
Hazel is going to have a go at improving this

**Comment by johnathan99j** [comment]
Any progress on this ?

**Comment by samozzy** [comment]
Hazel has written this and is going to send it to Team Proofreading today.

**Comment by johnathan99j** [comment]
Great :)

**Comment by samozzy** [comment]
> In an effort to make our website useful to new/prospective members, I propose either a new page or additions to the home and 'join' pages.
> These additions would be links to our SU page, members site ("log in with the details found on the sheet given out at new members, or contact us for help" but worded better) and Facebook members group, or instructions on who to contact to get added.
> I know we like our website to be client-facing, but its our space on the Internet and we can't run without members and I feel no further justification is necessary.

**Comment by FreneticScribbler** [comment]
This is now superseded by the join site ;)
