### ISSUE TITLE
Services Pages

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/Main-Website#12]
Something to describe what it is we do, and how we can help most people plan their event etc. Similar idea to the same pages on the [abandoned dev site](http://dev.nottinghamtec.co.uk/services/)

**Comment by samozzy** [comment]
Two suggestions:
a) Embedding the portfolio through wizardry
b) The return of packages. "Speakers of this size from £80 ex. VAT"

**Comment by tomtom5152** [comment]
>  Embedding the portfolio through wizardry

Depending how ambitious we were feeling, we could just make it the portfolio in a very snazzy way where it is all one one page with some form of scrolling.

Package are a definite thing we should add, give people a rough idea of at least how much they need to budget for.
