### ISSUE TITLE
Update PLI

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/Main-Website#14]
There's probably something illegal about displaying [out of date PLI](http://www.nottinghamtec.co.uk/PLI.pdf) if we should even show it at all.

**Comment by johnathan99j** [comment]
I'm all for displaying it but i don't know if we're meant to or not. Either way, here's the 2015-16 copy.
[PL Confirmation 2015.pdf](https://github.com/nottinghamtec/Main-Website/files/96311/PL.Confirmation.2015.pdf)

**Comment by tomtom5152** [comment]
Just given you write access to the repo, do you feel like updating it?

**Comment by johnathan99j** [comment]
I'll give it a go.

**Comment by johnathan99j** [comment]
I've updated master, no idea how to make it go live.
Edit: It seems to do it automatically after a certain amount of time.

**Comment by tomtom5152** [comment]
You just have to push to master, travis then takes over and rebuilds the site with the new content.

For future reference, GH also allows you to close issues from commit messages using `closes #<commit number>` syntax. Closed via a38c55b
