### ISSUE TITLE
Spellings

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#17]
The "Join TEC" box on the home page has spelling errors. The words "definitely" and "our" are spelled incorrectly.

**Comment by tomtom5152** [comment]
Did you intend to reopen this?

**Comment by samozzy** [comment]
I intended to close it with a "this was resolved in" thingy like on bitbucket but couldn't find the button.

**Comment by tomtom5152** [comment]
Hint, make you commit message `closes #17` and it would take care of it
automatically when you merged :P
