### ISSUE TITLE
Committee Pictures

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#19]
Jono's is v. v. unprofesh, especially for TD. Suggest changing to something less silly, but I can't find any examples :(

**Comment by tomtom5152** [comment]
Thats was my issue, if you can find a better one, please feel free to
create PR with it.

On Sun, 24 Jan 2016 at 16:43 samozzy notifications@github.com wrote:

> Jono's is v. v. unprofesh, especially for TD. Suggest changing to
> something less silly, but I can't find any examples :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nottinghamtec/Main-Website/issues/19.
> 
> ## 

Tom Price

**Comment by johnathan99j** [comment]
If this is better I'm happy to push it.
![johnathan](https://cloud.githubusercontent.com/assets/15066398/12585080/5ef55b8a-c442-11e5-874f-b2d816de26c6.jpg)

**Comment by samozzy** [comment]
Closed with #24

**Comment by johnathan99j** [comment]
It would appear that a new photo is required.

**Comment by harry-bridge** [comment]
## YES

**Comment by samozzy** [comment]
Forum photo is absolutely fine in my view.

**Comment by harry-bridge** [comment]
Better?

**Comment by samozzy** [comment]
Much better by my thoughts. Just wait for the man himself before merging.

**Comment by johnathan99j** [comment]
Fine by me (Just as well since it's committed to master ;) ) :shipit:
