### ISSUE TITLE
Production(s)

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#20]
?????

**Comment by nhyty** [comment]
??????

**Comment by johnathan99j** [comment]
To confirm, should it be Production Manager or Productions Manager ?

**Comment by samozzy** [comment]
Production singular.

**Comment by tomtom5152** [comment]
You want to change the file in the data directory I think, really quick and
easy fix.

I personally think it should be plural, this may well be something to fix
in the constitution tonight.

**Comment by johnathan99j** [comment]
As it didn't get changed should we just change it to the singular version ? 

A quick google shows that it's normally singular.(https://en.wikipedia.org/wiki/Production_manager_(theatre))

**Comment by tomtom5152** [comment]
That article would suggest that the production manager is responsible for making a single production happen. As TEC does many productions throughout the year and the PM has oversight of all of them, I still believe it should be plural (as is the email address). I feel we need a proper grammar nazi to come in on this.

**Comment by johnathan99j** [comment]
Due to his view on spelling I'd suggest bonniz.

**Comment by johnathan99j** [comment]
> Bobbinz:
> Productions (he manages them all)
> MICs could on big jobs be called Production Manager 

Judging from this I'm happy to close this issue. This also means that the constitution needs updating.

**Comment by samozzy** [comment]
Action Point: Update the constitution with Production -> Productions.
