### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/Main-Website#28]
Currently missing. Should be added

**Comment by johnathan99j** [comment]
As far as I know the Favoicon is just the icon used in the tab and favourites right ? This works fine for me.

**Comment by tomtom5152** [comment]
It will work fine if you ever viewed the old site as it will just use the
cached one. Currently it doesn't have one set for new visitors.

On Wed, 27 Jan 2016 at 21:48 Johnathan Graydon notifications@github.com
wrote:

> As far as I know the Favoicon is just the icon used in the tab and
> favourites right ? This works fine for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nottinghamtec/Main-Website/issues/28#issuecomment-175873059
> .
> 
> ## 

Tom Price

**Comment by johnathan99j** [comment]
I dug around in my cache and found this. (had to put in zip as it doesn't support uploading .ico)
Also where should this go in the site structure ? I'd guess at root ?
[favicon.zip](https://github.com/nottinghamtec/Main-Website/files/107434/favicon.zip)

**Comment by samozzy** [comment]
Favicons should live in ico and png form in the root folder with index. There's the option of persuading the browser to use it within <head> too. 
Using the favicon from dev. is absolutely a solution.

**Comment by johnathan99j** [comment]
#29

**Comment by johnathan99j** [comment]
This is now fixed and is waiting for merge #29
