### ISSUE TITLE
'New members' bits and pieces

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#30]
In an effort to make our website useful to new/prospective members, I propose either a new page or additions to the home and 'join' pages.
These additions would be links to our SU page, members site ("log in with the details found on the sheet given out at new members, or contact us for help" but worded better) and Facebook members group, or instructions on who to contact to get added.
I know we like our website to be client-facing, but its our space on the Internet and we can't run without members and I feel no further justification is necessary.

**Comment by johnathan99j** [comment]
I think a members page is a good idea and I'd be happy to give it a shot.

**Comment by tomtom5152** [comment]
We used to have join.nottinghamtec.co.uk page that got approximately 0 page views ever. The [get involved](https://github.com/nottinghamtec/Main-Website/blob/master/content/about/get-involved.md) page is comming along nicely with #11 and I would advise focusing on this one.

**Comment by samozzy** [comment]
Focussing on #11.
