### ISSUE TITLE
Full screen splash video

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/Main-Website#34]
I've only just figured out how to do this hence why I'm only just suggesting it, but how would a full screen splash video on the homepage sound, sort of along the lines of http://www.gitkraken.com/

**Comment by harry-bridge** [comment]
as long as 
- It isn't in potato quality
- It is hosted somewhere where it can load quickly

**Comment by tomtom5152** [comment]
Obviously a video would need making for this, I was just trying to get a
feel for if people thought it was a good idea. In terms of hosting, I would
happily put it on my personal S3 account for speed.

**Comment by harry-bridge** [comment]
If we can get something made that that is nice enough to have on there then I'd be up for it

**Comment by johnathan99j** [comment]
I happen to be a perfectly decent quality !

**Comment by johnathan99j** [comment]
I happen to be a very good quality! !
On 3 Feb 2016 13:37, Harry Bridge <notifications@github.com> wrote:as long as 

It isn't in potato qualityIt is hosted somewhere where it can load quickly

**Comment by tomtom5152** [comment]
Speaking to Alex he suggested the parallax thing he made for the week one stall would be a good fit, certainly as a stop gap to see what we think. Don't know where this file is mind.

**Comment by samozzy** [comment]
The file is at least on Playback 1. That's a nice shout.
Harry showed me his version of the YouTube video autoplaying which is quite nice.

**Comment by samozzy** [comment]
@tomtom5152 If I get the file, where does it need to go?

**Comment by tomtom5152** [comment]
@samozzy Depends how large the file is

**Comment by harry-bridge** [comment]
/static/videos/ seems a sensible place to put it

**Comment by harry-bridge** [comment]
or S3

**Comment by tomtom5152** [comment]
@pickleshb If it's larger than 50MB GH won't be happy about it so it might have to be S3 or techost etc

**Comment by samozzy** [comment]
@tomtom5152 I think it's larger.

**Comment by harry-bridge** [comment]
@samozzy do we have the file located?

**Comment by tomtom5152** [comment]
@samozzy Smugmug do offer video hosting, @wjdp knows more about this

**Comment by samozzy** [comment]
@pickleshb Frustratingly the only place I'm aware of it being is the playback racks, or Alex's machine.

**Comment by wjdp** [comment]
SmugMug do, upload video and get links to various sizes.

See http://api.smugmug.com/api/v2/image/dbwbrKf-1!sizedetails (look at VideoSizes)

**Comment by samozzy** [comment]
@wjdp That's convenient - look what I've found https://nottinghamtec.smugmug.com/Reference/Random-Tec-Stuff/i-p8Bcdtn/A
