### ISSUE TITLE
New committee

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#36]
Uhoh.

**Comment by johnathan99j** [comment]
#37 Will close this, just waiting on @samozzy to make words

**Comment by harry-bridge** [comment]
... And photos

**Comment by samozzy** [comment]
Photos aren't being taken until after Easter now (because we're waiting until we have a treasurer).

**Comment by tomtom5152** [comment]
Facebook photos will do in the meantime, it's more the words we need from you Sam

**Comment by harry-bridge** [comment]
I'll get a better photo for Ben, but yes many words are needed

**Comment by samozzy** [comment]
Words committed.

**Comment by harry-bridge** [comment]
Looks good, will have a look properly later and find some semi decent
photos
