### ISSUE TITLE
RAMS

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/Main-Website#42]
Having spoken to Vik a bit, we think having all our RAMS on the website might be a good idea. This also allows us to potentially use the website as a data source for CDM integration in RIGS (the game I know you have all been waiting for).

So far I can see two approaches to it. 
1. Firstly we could use a data file as we have with the committee. This data file serves as the raw data source for RIGS, and hugo compiles it into a single page. Downside of this is it is still a monolithic document as with the current RAMS document, but at least it isn't MS Word.
2. Alternatively, we create a custom type and then generate the pages as normal. This preserves the advantage to keeping each of the RAMS separate, but does this make it easier/harder to maintain?(not something you want with H&S documentation). We would then need to use the built in Hugo XML generator to provide a data source for RIGS, either that or traverse the directory for multiple files to use.
   I personally don't like either of these suggestions.

There is a way to combine both of these, but it requires a plugin, something Hugo doesn't support. Converting to Jekyll would allow a custom plugin, something @wjdp is quite familiar with. I don't know how much work this would be, the template engine is very similar so it would just require a bit of converting there, but that's about all I can see so far.

Thoughts gentleman?

**Comment by davidtaylorhq** [comment]
I think 1 massive file should be avoided as much as possible. 

Having version control on RAMS would be great! However, the RAMS document is not a simple thing that could be reproduced in markdown, I seem to remember it having some pretty complicated table structures.

**Comment by harry-bridge** [comment]
I'm with David on less giant data files, It's a massive document so I also think pages would't work. If we're going to go down the route of version controlling the RAMS is there a way to have it in a different repo to keep things separate? Or we just say fuck it and plonk the PDF in

**Comment by samozzy** [comment]
@pickleshb I'm not saying that storing it on the wiki provides version control, but...

**Comment by davidtaylorhq** [comment]
@pickleshb Agree a separate repo would be ideal

**Comment by tomtom5152** [comment]
@samozzy It provides version control, but it doesn't provide a nice way to generate a file for consumption by RIGS.

A separate repo might be an option, but it does introduce potential complications. It does give two things that need to be updated though.

**Comment by davidtaylorhq** [comment]
@tomtom5152 What are we actually trying to achieve here? If all you want is the RAMS on the website then just use the PDF. If you want auto-generated CDM RAMS packs specific to each rigs then that's a monolithic task

**Comment by samozzy** [comment]
@davidtaylorhq I feel like a RAMS document that is sectioned appropriately so that it can be split into CDM packs would make sense. Somehow if this can be auto-split into many smaller PDFs that can make a CDM pack it would make sense. If this was automagic when the master document is updated that makes the world of sense.

**Comment by tomtom5152** [comment]
The first idea is just to put the RAMS on the website in a sensible way. This should be done in a way that allows us to add the CDM packs to RIGS at a later date. I guess the main goal is to give us the data in a format that could be processed as part of CDM, the pretty version is just for internal use. (from conversations with Vik, CDM pack generation is something RIGS would really benefit from)

**Comment by davidtaylorhq** [comment]
@tomtom5152 Do we seriously need to do all this, or is it just TEC self-regulating ourselves into the ground again?

**Comment by harry-bridge** [comment]
From talking to Matt about this he was happy that as we _should_ be carrying an up to date RAMS in every healthy safe kit which is on every rig then it is fine in any document we produce to say, 
- Process _x_ done in accordance with RAMS see pp 66-68 

So if the police turn up on site and ask for our healthy safe stuff we give them our CDM pack we've made and our big box of RAMS

**Comment by harry-bridge** [comment]
The thing he really wanted us to be able to do was print off the training sheet of anyone named in the document, but that isn't a discussion for here!

**Comment by davidtaylorhq** [comment]
@pickleshb If this is all we need then putting hours/days/months into making the RAMS RIGS-consumable is a pointless waste of time

**Comment by harry-bridge** [comment]
@davidtaylorhq It is, we just have to really make sure we carry an up to date RAMS to **every** rig

**Comment by davidtaylorhq** [comment]
@pickleshb We should be doing this already. Every H&S box/bag has a folder with the RAMS in it. As far as I know, this is up to date

**Comment by samozzy** [comment]
@davidtaylorhq I agree with this. If that's all that is required, it is very achievable.
