### ISSUE TITLE
Home page fit

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#47]
The top panel of the home page should all be viewable without scrolling on all devices.
That is to say that, without scrolling, users should see "scroll for more".

**Comment by samozzy** [comment]
Only resolved for mobile devices, still too big on my desktop.
![desktop](https://cloud.githubusercontent.com/assets/15388319/14283546/b5179fb6-fb3b-11e5-9b7d-09bb678bb4b0.png)

**Comment by harry-bridge** [comment]
@samozzy Grrr, I'll have a look at this in a bit
