### ISSUE TITLE
Mobile issues: other pages

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#50]
The floating menu gets in the way of the page text.
Solution: A back to top arrow in the bottom right.
![responsive oops](https://cloud.githubusercontent.com/assets/15388319/14284434/734cb108-fb3f-11e5-806b-c0fe27998fc2.png)

**Comment by harry-bridge** [comment]
@samozzy Danke I'll fix this too

**Comment by harry-bridge** [comment]
Also contact-us is funky on mobile 
<img width="412" alt="screen shot 2016-04-05 at 18 42 45" src="https://cloud.githubusercontent.com/assets/5897290/14292064/4a1614b8-fb5e-11e5-85ed-8f63597c683e.png">

**Comment by samozzy** [comment]
Well that's a bit odd.
