### ISSUE TITLE
Ross want's some things

### ISSUE THREAD

**Issue by harry-bridge** [nottinghamtec/Main-Website#55]
- **Kit lists**
  - A list of things that we have so people can see quickly at a glance
- **Venues** (I did this)
- **Acts**
  - List of people we've worked with, makes us look better
- **What we can do**
  - Similar to case studies I feel
- **Case studies**
  - Some nice looking events that we've done
  - Examples of some small to large events
- **Packages**
  - We commonly offer this stuff together, call us to see what we can do for you
- **Sense of cost**
  - Could be in case studies, no sure whether this is needed

Results of a pub conversation so make of this what you will

**Comment by johnathan99j** [comment]
So I'm thinking something along these lines, a new menu section on the top level with "Why Us?" as the lable that has in it things like:

- Out Kit
- Packages
- Acts
- Venues
- etc.

A possible acts page, obviously the blurb at the top needs work. Thoughts? Data taken from the wiki.

![image](https://user-images.githubusercontent.com/15066398/31718942-9de0c0e2-b409-11e7-89df-313218439a81.png)

**Comment by Jason-TEC** [comment]
Is there a reason this didn't happen?
