### ISSUE TITLE
About has issues 

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/Main-Website#62]
It appears we have created DOM infinity somehow 
![img_0868](https://cloud.githubusercontent.com/assets/2250882/21139961/6ab2181c-c12d-11e6-9648-6013f99f5149.PNG)

**Comment by davidtaylorhq** [comment]
fixed this, no idea why it happened in the first place

http://shouldiblamecaching.com/

**Comment by davidtaylorhq** [comment]
It's returned

**Comment by harry-bridge** [comment]
Fixed in #67
