### ISSUE TITLE
Video causing excess CPU usage

### ISSUE THREAD

**Issue by davidtaylorhq** [nottinghamtec/Main-Website#64]
Tempo reports his university laptop using 30% CPU for the video, this is bad. Needs investigation

**Comment by davidtaylorhq** [comment]
Specs:
4 core i5-2450M 2.5GHz. 8GB RAM. Decent SSD. On-board graphics card (driver is Intel HD Graphics 3000)

Chrome

**Comment by tomtom5152** [comment]
Checked on a similar spec machine from around the same era running Windows 7 ultimate x64 which is more viruses than Windows (not my machine), got a consistent 10% peaking at 18% with software decoding. Suggest this might be an extreme example.

**Comment by johnathan99j** [comment]
Given this hasn't come up since and I also can't replicate it I'm calling it an outlier.
