### ISSUE TITLE
Move to Jekyll

### ISSUE THREAD

**Issue by harry-bridge** [nottinghamtec/Main-Website#69]
As has become apparent recently HUGO isn't stable for us going forward so @tomtom5152 and I think that switching over to Jekyll will be better for us in the long run, it won't be that much effort and could open up more possibilities in the future that we can't do with HUGO

**Comment by davidtaylorhq** [comment]
@pickleshb Many efforts, but I agree. Why did we even go for Hugo in the first place?

**Comment by harry-bridge** [comment]
@davidtaylorhq blame @tomtom51512

**Comment by tomtom5152** [comment]
@davidtaylorhq That was entirely my choice, based on no experience, I now think jekyll is the better platform. As Harry said, it won't be that much effort, maybe just changing some of the variables and syntax in the templates, and rewriting the committee page logic (not difficult)

**Comment by davidtaylorhq** [comment]
@tomtom5152 Fair enough - wasn't trying to be rude about the choice, just interested. 
Do they use the same template syntax?

**Comment by harry-bridge** [comment]
@tomtom5152 I'll probably have a bash at the end of exams

**Comment by FreneticScribbler** [comment]
Intresting that Bootstrap have just switched the other way. Going to take a look at sticking with Hugo (no arguments with Ruby is a massive plus to me...)

**Comment by FreneticScribbler** [comment]
Go good, Ruby bad
