### ISSUE TITLE
Committee 17/18

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/Main-Website#75]
Need to change the things.

**Comment by alexdaniel654** [comment]
The first word of the paragraph about Ross is wrong. Should be Ross' instead of Ross's.

**Comment by davidtaylorhq** [comment]
For a simple noun, you would be correct. For a name, I believe Ross's is correct

From [here](https://en.oxforddictionaries.com/punctuation/apostrophe)
> With personal names that end in -s: add an apostrophe plus s when you would naturally pronounce an extra s if you said the word out loud:
> - He joined Charles’s army in 1642.
> - Dickens's novels provide a wonderful insight into Victorian England.
> - Thomas's brother was injured in the accident.

**Comment by alexdaniel654** [comment]
I stand corrected, although I would argue Ross is a VERY simple noun!
