### ISSUE TITLE
Image Optimisation

### ISSUE THREAD

**Issue by johnathan99j** [nottinghamtec/Main-Website#81]
So I've discovered [an image optimisation bot](https://github.com/marketplace/imgbot), any objections to me running it through this repo? I'd suggest PyRIGS as well but I can't really think of any images on the site that come from the repo.

**Comment by davidtaylorhq** [comment]
@johnathan99j No harm in letting it create a PR, then we can review any changes

**Comment by johnathan99j** [comment]
Well everything's passed on #82 and as it's lossless compression I see no reason not to merge it.

**Comment by johnathan99j** [comment]
Closed with #82
