### ISSUE TITLE
Wiki Competent Persons - Generators

### ISSUE THREAD

**Issue by Jason-TEC** [nottinghamtec/Main-Website#83]
Is someone able to add a column for generators to the wiki...

Would be really handy

**Comment by BenWoodford76** [comment]
Give me a list of who can do it and i'll sort it

**Comment by BenWoodford76** [comment]
Done

**Comment by Jason-TEC** [comment]
Thanks Ben

**Comment by johnathan99j** [comment]
While I realise that @Jason-TEC is new to GitHub you should try to keep anything here related to the public website only.
