### ISSUE TITLE
Twitter address is wrong

### ISSUE THREAD

**Issue by bobbinz** [nottinghamtec/Main-Website#86]
The link to twitter is incorrect. I would update it but I simply have no idea how!

**Comment by davidtaylorhq** [comment]
Done

**Comment by johnathan99j** [comment]
In 29988504e1c19505789d4f6ab41e3fe72985a554 and b8150c1835e59cec237887b1320f4f5d8c8e9fdc for reference.

**Comment by davidtaylorhq** [comment]
@johnathan99j and https://github.com/nottinghamtec/Main-Website/commit/2adbb041df7f863e8f5492947035de1195eb1c6a because I accidently mashed the keyboard when clicking save the first time 😉

**Comment by bobbinz** [comment]
I did that once. On postec hit chmod 644 / rather than chmod 644 *

Broke quite a lot of stuff.

**Comment by tomtom5152** [comment]
@bobbinz I think I remember this, there was much swearing
