### ISSUE TITLE
Room Number

### ISSUE THREAD

**Issue by bobbinz** [nottinghamtec/Main-Website#87]
Reads C45 instead of C87

**Comment by bobbinz** [comment]
Fixed in 3f9cb20

**Comment by johnathan99j** [comment]
@bobbinz have a look at https://help.github.com/articles/closing-issues-using-keywords/

TL;DR
`Update contact.md will close #87` Would automatically close the issue when you pushed, very useful.

**Comment by bobbinz** [comment]
Blimey that's far too complicated.
