### ISSUE TITLE
PLASA Branding

### ISSUE THREAD

**Issue by alexdaniel654** [nottinghamtec/Main-Website#90]
Looks like PLASA have had a minor re-brand. Should probably update the logo to [this new one](https://www.plasa.org/downloadarea/plasa/) but in grayscale à la the current one on our website.

**Comment by tomtom5152** [comment]
You'd think they would provide a vector version or at least one without a white halo on the transparency 🙄

Do they actually use a grayscale one anywhere, I don't really care what their opinion on it is, but some companies get funny about you modifyingtheire logo in any way at all so would be nice to not piss them off

**Comment by alexdaniel654** [comment]
I seem to remember having to make an eps myself last time. They use an all white version on the bottom of their website, could probably do the same.

**Comment by alexdaniel654** [comment]
![PLASA_white_2019_HR](https://user-images.githubusercontent.com/23356429/54164068-342f4c00-4453-11e9-8e37-b8f873522a16.png)
Have a high res white PLASA logo.
